### ISSUE TITLE
Support --kubeconfig argument to kubectl

### ISSUE THREAD

**Issue by dcj** [chrisbarrett/kubernetes-el#4]
How can I specify my kubeconfig file?

**Comment by noorul** [comment]
I think you need to have the client configured outside of emacs

**Comment by dcj** [comment]
It works if I hard-code my  ~/.kube/config file but when one has multiple Kubernetes clusters,
it is necessary to specify an alternate config file via the --kubeconfig command line argument.  A nice feature for kubernetes.el to support would be some way of specifying command line options to be used in conjunction with kubectl.  I tried just adding this option to the variable that contains the name/path to kubectl but that didn't work....

**Comment by noorul** [comment]
Isn't contexts used for this purpose. In kubeconfig you can define multiple clusters as contexts. Context switch is supported by this mode.

**Comment by chrisbarrett** [comment]
It wouldn't be hard to support this. It's not a priority for me, since contexts with different clusters should provide you the features you need, but I'll look at this sometime. 👍

**Comment by chrisbarrett** [comment]
@dcj: this is now implemented. You can press `c` in the overview buffer and specify a kubeconfig file by typing `= f`. As in any magit popup, you can type `C-x C-s` to save your selected flags to your custom file so that the settings persist across Emacs sessions.

The way this works with the rest of the package is kind of a glorious hack, so please let me know if there are any flaky interaction issues or bugs here. 😅
