### ISSUE TITLE
Leaving an exec session?

### ISSUE THREAD

**Issue by seanleblanc** [chrisbarrett/kubernetes-el#95]
I've noticed I have to manually click back in the overview frame, or I have to exit the exec session by typing exit. Other Emacs bindings do not seem to work? I'm using this with spacemacs (non-Evil mode) - anyone else notice this?

**Comment by chrisbarrett** [comment]
The exec buffers are in the built-in term mode. There are some idiosyncrasies to the way terminals work in Emacs so that they can pass keys to terminal processes in a reasonable way. 

This SE answer should give you some background:

https://unix.stackexchange.com/questions/148581/in-emacs-term-mode-what-is-char-mode-and-line-mode-how-do-they-differ

**Comment by seanleblanc** [comment]
Ah, thank you. I never knew that and have been using Emacs for some time. Learn something new all the time about it, though. 

So, basically, with default bindings, do a C-c C-j to switch to line mode, then things like C-b, C-x o, will work as expected, then Ctrl-c Ctrl-k to move back to char mode.

**Comment by noorul** [comment]
Closing this.
